Fix(react-native) add missing `new`
Fixes this error on startup:

```
this.wsServer = _ws2.default.Server({ server: this.httpServer });
                                 ^

TypeError: Class constructor WebSocketServer cannot be invoked without 'new'
    at new Server (.../node_modules/@storybook/react-native/dist/server/index.js:48:34)
```