Remove spurious flag to build in Ember
There’s no need to specify a port to only build, and
doing so produces this error:

error: unknown option `-p'